name: "Fetch vercel preview"
description: "Fetch the latest vercel preview link that can be used for e2e testing, or benchmarking for example."
inputs:
  vercel_token:
    description: "The vercel token to use for auth"
    required: true
  vercel_project_id:
    description: "The vercel project so this knows which project to fetch from"
    required: true
outputs:
  preview_url:
    description: "The preview url from vercel"
runs:
  using: "node16"
  main: "dist/index.js"
